<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii translation' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
    //views/index.php
    'Migrations' => 'Databázové struktury',
    'Migrate up' => 'Zvýšit verzi databáze',
    'Apply all un-applied migrations' => 'Aplikuje všechny čekající migrace',
    'Toggle Dropdown' => 'Přepnout nabídku',
    'Migrate one up' => 'Zvýšit o jednu verzi',
    'Apply the first un-applied migration' => '',
    'Optimize database' => 'Optimalizovat databázi',
    'Clear database' => 'Vyčistit databázi',
    'Drop all tables from database' => 'Smaže všechny tabulky v databázi',
    'Are you REALLY sure to DROP ALL TABLES from the database? This operation CAN NOT be undone!' => 'OPRAVDU si přejete SMAZAT VŠECHNY TABULKY v databázi? Tato operace NEMŮŽE být vrácena!',
    'Other options' => 'Další možnosti',
    'New migrations' => 'Čekající skripty',
    'Optimize all database tables' => 'Optimalizuje všechny tabulky v databázi',
    'Name' => 'Název',
    'Path' => 'Cesta',
    'Applied migrations' => 'Aplikované skripty',
    'Apply time' => 'Aplikováno',
    'Version' => 'Verze',
    'Module' => 'Modul',
    'Migrate down to' => 'Snížit na tuto verzi',
    'Are you sure to decrease database structures to this version? Data from newer migrations may be lost!' => 'Opravdu si přejete snížit verzi databáze na tuto verzi? Může dojít ke ztrátě dat novějších migrací!',

    //views/index.php
    'Migration result' => 'Výsledek migrace',

    //Migration
    'Base migration is already applied.' => 'Základní migrace již byla aplikována.',
    'Migration {name} successfully applied.' => 'Skript {name} byl úspěšně aplikován.',
    'Migration {name} for module {module} successfully applied.' => 'Skript {name} modulu {module} byl úspěšně aplikován.',
    'Failed to apply migration {name}.' => 'Došlo k chybě při aplikaci skriptu {name}.',
    'Failed to apply migration {name} for module {module}.' => 'Došlo k chybě při aplikaci skriptu {name} modulu {module}.',
    'Migration {name} successfully reverted.' => 'Skript {name} byl úspěšně zvrácen.',
    'Migration {name} for module {module} successfully reverted.' => 'Skript {name} modulu {module} byl úspěšně zvrácen.',
    'Failed to revert migration {name}.' => 'Došlo k chybě při zvrácení skriptu {name} modulu {module}.',
    'Failed to revert migration {name} for module {module}.' => 'Došlo k chybě při zvrácení skriptu {name}.',
    'No new migration found. Your system is up-to-date.' => 'Nebyly nalezeny žádné nové migrační skripty. Struktura databáze je aktuální.',
    'Successfully applied {count, plural, one{one migration} other{# migrations}}.' => 'Úspěšně {count, plural, one{aplikována jedna migrace} few{aplikovány # migrace} other{aplikováno # migrací}}.',
    'The step argument must be greater than 0.' => 'Parametr step musí být větší, než 0.',
    'No migration has been done before.' => 'Nebyl nalezen žádný skript ke zvrácení.',
    'Successfully reverted {count, plural, one{# migration} other{# migrations}}.' => '{count, plural, one{Jeden skript byl úspěšně zvrácen} few{# skripty byly úspěšně zvrácny} other{# skriptů bylo úspěšně zvráceno}}.',

    //FtsMigration
    'Schema for table {tbl} not found.' => 'Struktura tabulky {tbl} nebyla nalezena.',

    //AdminController
    'This command is available only in development.' => 'Tento příkaz je dostupný pouze ve vývojovém prostředí.',
    'All tables was successfully dropped.' => 'Všechny tabulky byly úspěšně smazány.',
    'Error while dropping tables.' => 'Došlo k chybě při mazání tabulek databáze.',
    'All tables was successfully optimized.' => 'Všechny tabulky byly úspěšně optimalizovány.',
    'Error while optimizing tables.' => 'Došlo k chybě při optimalizaci tabulek databáze.',
);
